
version: "3"

services:
  app:
    image: node
    command: npm start
    ports:
      - "80:8008"
    links:
      - db
    working_dir: /nodeApp
    environment:
      SEQ_DB: node-db-postgres
      SEQ_USER: postgres
      SEQ_PW: 123456
      PORT: 8008
      DATABASE_URL: postgres://postgres:123456@127.0.0.1:5432/node-db-postgres
    volumes:
      - ./:/nodeApp
  db:
    image: postgres
    container_name: db
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

# services:
#   app: 
#     image: emiliapavlova/nodeApp
#     ports: 
#       - 80:8008
#     command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
#     depends_on:
#       - db
#     environment:
#       - DATABASE_URL=postgres://postgres:123456@db:5432/node-db-postgres
#       - PORT=8008   
#   db:
#     image: postgres
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=123456
#       - POSTGRES_DB=node-db-postgres